//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khaira_Freight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planner
    {
        public int event_id { get; set; }
        public string status { get; set; }
        public int trip { get; set; }
        public string activity { get; set; }
        public Nullable<int> driver_id { get; set; }
        public string driver_name { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public Nullable<int> truck { get; set; }
        public string trailer { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    }
}
